on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: Set API key
      run: echo "API_KEY=1234" >> $GITHUB_ENV
    - name: echo API key
      run: echo "$API_KEY"
    
